syntax = "LuaJIT"
line_endings = "Unix"
call_parentheses = "Always"
quote_style = "AutoPreferDouble"
space_after_function_names = "Never"
indent_type = "Spaces"
indent_width = 2
column_width = 120
[sort_requires]
enabled = true
